Repository calstates4/s4-shared-components, pull requests merged in 2023-08, with the labels that each got.

#17 CSU-203: Students can view a list of Opportunities
  src/components/02-components/offering-card/offering-card.tsx
  src/components/02-components/offering-form/offering-form.stories.tsx
  src/components/02-components/offering-form/offering-form.tsx
  src/components/02-components/offering-page/offering-page.tsx
  src/components/02-components/opportunity-card/opportunity-card.stories.tsx
  src/components/02-components/opportunity-card/opportunity-card.tsx
  src/components/02-components/opportunity-list/opportunity-list.stories.tsx
  src/components/02-components/opportunity-list/opportunity-list.tsx
  src/index.ts
Labels: 🎉 Passes Code Review, 🎉 Passes Functional Review, 🎉 Ready to Merge

#25 CSU-297: Export Time log Table component
  src/index.ts
Labels: 🎉 Passes Code Review, 🎉 Passes Functional Review, 🎉 Ready to Merge

#21 feat: add wrapper component
  src/components/02-components/wrapper/wrapper.stories.tsx
  src/components/02-components/wrapper/wrapper.tsx
  src/index.ts
Labels: 🎉 Passes Code Review, 🎉 Passes Functional Review, 🎉 Ready to Merge

#22 Adds tokens to storybook and a stat with icon component
  src/components/00-tokens/color/color.tsx
  src/components/00-tokens/color/colors.stories.tsx
  src/components/00-tokens/icon/material/material-icons.stories.tsx
  src/components/00-tokens/icon/material/material-icons.tsx
  src/components/00-tokens/spacing/spacing.stories.tsx
  src/components/00-tokens/typography/typography.stories.tsx
  src/components/00-tokens/typography/typography.tsx
  src/components/02-components/cta-card/cta-card.tsx
  src/components/02-components/stat-with-icon/stat-with-icon.stories.tsx
  src/components/02-components/stat-with-icon/stat-with-icon.tsx
  src/index.ts
Labels: 🎉 Passes Code Review, 🎉 Passes Functional Review, 🎉 Ready to Merge

#23 Update typography
  src/components/00-tokens/typography/typography.tsx
  src/theme/index.ts
Labels: 🎉 Passes Code Review, 🎉 Passes Functional Review, 🎉 Ready to Merge

#27 CSU-297: Add pager to time log table component
  src/components/02-components/experience-page/experience-page.tsx
  src/components/02-components/time-log-table/time-log-table.stories.tsx
  src/components/02-components/time-log-table/time-log-table.tsx
Labels: 🎉 Passes Code Review, 🎉 Passes Functional Review, 🎉 Ready to Merge

#29 feat: add data table
  package-lock.json
  package.json
  src/components/02-components/data-table/data-table.stories.tsx
  src/components/02-components/data-table/data-table.tsx
  src/index.ts
Labels: 🎉 Passes Code Review, 🎉 Passes Functional Review, 🎉 Ready to Merge

#28 CSU-NOTICKET: Update branding menu
  README.md
  src/components/02-components/branding-bar/branding-bar.stories.tsx
  src/components/02-components/branding-bar/branding-bar.tsx
Labels: 🎉 Passes Code Review, 🎉 Passes Functional Review, 🎉 Ready to Merge

#33 fix: upgrade @remix-run/testing package for module include errors
  package-lock.json
  package.json
Labels: 🎉 Passes Code Review, 🎉 Passes Functional Review, 🎉 Ready to Merge

#37 fix: wip from collab session
  src/components/02-components/data-table/data-table-experiences.tsx
  src/components/02-components/data-table/data-table-staff.tsx
  src/components/02-components/data-table/data-table-toolbar.generic.tsx
  src/components/02-components/data-table/data-table.data.tsx
  src/components/02-components/data-table/data-table.stories.tsx
  src/components/02-components/data-table/data-table.tsx
  src/components/02-components/form/form-staff.tsx
  src/components/02-components/form/form.stories.tsx
  src/components/02-components/form/form.tsx
  src/components/04-pages/generic/data-table-page.stories.tsx
  src/components/04-pages/generic/data-table-page.tsx
  src/components/04-pages/partners/organization/experiences/experiences.stories.tsx
  src/components/04-pages/partners/organization/experiences/experiences.tsx
  src/components/04-pages/partners/organization/staff/staff.stories.tsx
  src/components/04-pages/partners/organization/staff/staff.tsx
  src/index.ts
Labels: 🚧 Work in Progress

#34 Staff listing data table and page
  src/components/02-components/data-table/data-table-experiences.tsx
  src/components/02-components/data-table/data-table-toolbar.generic.tsx
  src/components/02-components/data-table/data-table.data.tsx
  src/components/02-components/data-table/data-table.stories.tsx
  src/components/02-components/data-table/data-table.tsx
  src/components/02-components/form/form.stories.tsx
  src/components/02-components/form/form.tsx
  src/components/04-pages/generic/data-table-page.stories.tsx
  src/components/04-pages/generic/data-table-page.tsx
  src/components/04-pages/partners/organization/experiences/experiences.stories.tsx
  src/components/04-pages/partners/organization/experiences/experiences.tsx
  src/index.ts
Labels: 👍 Ready for Review

#35 fix: update readme
  README.md
Labels: 🎉 Passes Code Review, 🎉 Passes Functional Review, 🎉 Ready to Merge
